---
kind: pipeline
type: docker
name: build

volumes:
  - name: bundle
    host:
      path: /home/data/drone/gems
  - name: keys
    host:
      path: /home/data/drone/key_cache

spec_step_common: &spec_step_common
  pull: if-not-exists
  volumes:
  - name: bundle
    path: /bundle
  - name: keys
    path: /ssh_keys
  commands:
  - rm -fr Gemfile.lock gemfiles/
  - eval $(ssh-agent -s)
  - ssh-add /ssh_keys/id_rsa
  - bundle install -j 5
  - bundle exec appraisal install
  - bundle exec appraisal bundle exec rspec

steps:
- name: build on ruby2.2
  image: abakpress/ruby-app:2.2-latest
  environment:
    BUNDLE_PATH: /bundle/2.2
  <<: *spec_step_common

- name: build on ruby2.3
  image: abakpress/ruby-app:2.3-latest
  environment:
    BUNDLE_PATH: /bundle/2.3
  <<: *spec_step_common

- name: build on ruby2.4
  image: abakpress/ruby-app:2.4-latest
  environment:
    BUNDLE_PATH: /bundle/2.4
  <<: *spec_step_common

- name: release
  image: abakpress/gem-publication:latest
  pull: if-not-exists
  when:
    event: push
    branch: master
    status: success
  commands:
    - release-gem
