build:
  test:
    image: abakpress/dind-testing
    pull: true
    privileged: true
    volumes:
      - /home/data/drone/images:/images
      - /home/data/drone/gems:/bundle
      - /home/data/drone/key_cache:/ssh_keys
    environment:
      - COMPOSE_FILE_EXT=drone
      - RUBY_IMAGE_TAG=2.2-latest
    commands:
      - wrapdocker docker -v

      - fetch-images
        --image whilp/ssh-agent

      - dip ssh add -T -v /ssh_keys -k /ssh_keys/id_rsa
      - dip provision
      - dip rspec

  release:
    image: abakpress/gem-publication
    pull: true
    when:
      event: push
    commands:
      - release-gem
